### ISSUE TITLE
"Non-unique Mixin config name" crash on launch

### ISSUE THREAD

**Issue by encode42** [ahdplayer/NotfiyMe-Fabric#1]
Both [Organized Tabs](https://modrinth.com/mod/organized-tabs) and NotifyMe contain the `modid.mixins.json` file within their archives. I'm not a mod developer, but compared to other mods, this file is usually named `<the mod name>.mixins.json`, ie `notifyme.mixins.json`.

Stack trace from the crash, since us developers like to see them :)

```java
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.RuntimeException: Non-unique Mixin config name modid.mixins.json used by the mods organized_tabs and modid
	at org.quiltmc.loader.impl.launch.common.QuiltMixinBootstrap.init(QuiltMixinBootstrap.java:107)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:147)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	... 9 more
```

**Comment by ahdplayer** [comment]
I will look into it. Thanks for reporting.

**Comment by ahdplayer** [comment]
That's weird, are you sure its related to this mod? Because the mixin config is already named notifyme.mixins.json. @Encode42

**Comment by encode42** [comment]
From the latest jar from modrinth ([1.0](https://modrinth.com/mod/notifyme/version/1.0))

![image](https://user-images.githubusercontent.com/34699884/206249620-d775d044-6d30-479f-8434-5d02e26352f2.png)

**Comment by ahdplayer** [comment]
oof it seems like its a old version, i will compile and upload the new version asap. Thank you.

**Comment by ahdplayer** [comment]
@Encode42 updated on both modrinth and github, should be good now
